var swap_lib = [
	["president", "High Wizard"],
	["prime minister", "Emperor"],
	["senator", "Elf King"],
	["congressman", "Arch-Demon"],
	["dictator", 'resident cool guy'],
	['economist', 'Black Knight'],
	['lawyer', 'River Spirit'],
	['judge', 'Angry Mountain Dwarf'],
	['Queen', 'Royal Fanniwinkle'],
	['Pope', 'Supreme Scientologist'],
	['actor', 'Wicker Weaver'],
	['u.s.', 'Farmville'],
	['united states', 'Farmville'],
	['middle east', 'Middle Earth'],
	['canada', 'Beyond the Wall'],
	['russia', 'Mount Doom'],
	['iran', 'Tron'],
	['iraq', 'Habbo Hotel'],
	['israel', 'Narnia'],
	['england', 'The Existential Plane'],
	['great brittain', 'Super Duper Great Brittain'],
	['syria', 'Mordor'],
	['ireland', 'The Shire'],
	['france', 'Sherwood Forst'],
	['japan', 'The island of the Misfit Toys'],
	['china', 'Terrabithia'],
	['al-quaeda', 'The Troll Coalition'],
	['isis', 'Not so great Tailgate Party'],
	['hamas', 'United Church of Charzar'],
	['taliban', 'The Peoples front of Judea'],
	['government','Bowling Team'],
	['obama', 'Big Puba'],
	['stephen harper', 'Voldemort'],
	['hillary clinton', 'Megatron'],
	['bernie sanders', 'Mr Clean'],
	['dick cheney', 'Hannibal Lector'],
	['valdimir putin', 'Hans Moleman'],
	['steve jobs', 'Captain Crunch'],
	['donald trump', 'Danny Devito'],
	['white house', 'Playboy Mansion'],
	['supreme court', 'Fightclub'],
	['negotiation', 'square dance'],
	['terrorist', 'Lion Tamer'],
	['terror', 'interpretive dance'],
	['constitution', 'coloring book'],
	['declaration', 'intense gibbeish'],
	['drone', 'sex-bot'],
	['arab spring', 'mardi gras'],
	['climate change', 'the true meaning of christmas'],
	["new study", "tumblr post"],
	["electric", "nuclear"],
	["electronic", "sonic"],
	["nuclear", "magic"],
	["smartphone", "pokedex"],
	["device", "box"],
	["tablet", "portable porn machine"],
	["hackers", "cybermen"],
	["guilty", "guilty as fuck"],
	["victim", "friend of alligator"],
	["deviant", "marmot"],
	["prosecutor", "schoolbus driver"],
	["atorney", "hobbit"],
	["money", "mun muns"],
	["industry", "fishmarket"],
	["investment", "sandwhich"],
	["stock market", "turtle race"],
	["bank", "beanstock"],
	["stocks", "paper planes"],
	["deficit", "shitstorm"],
	["economy", "telemarketing scam"]
];

function makeSubsitutions(text){
	for (var i=0;i < swap_lib.length; i++){
		text = text.replace(swap_lib[i][0], swap_lib[i][1]);		
	}
	return (text);
}
$("p, h1, h2, h3, h4, h5, h6, span").each(function(i , current){
	var text = $(current).text();
	$(current).html(makeSubsitutions(text));
});